services:
  api1: &api
    image: ghcr.io/sudanvannin/rinha-2026-python/api@sha256:fd8c73cf9a19acc60441fa5038d6e481e34f4174d27038cd576eacf9d092078e
    platform: linux/amd64
    hostname: api1
    restart: unless-stopped
    environment:
      PORT: "8080"
      OPENBLAS_NUM_THREADS: "1"
      OMP_NUM_THREADS: "1"
      MKL_NUM_THREADS: "1"
      NUMEXPR_NUM_THREADS: "1"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "100MB"

  api2:
    <<: *api
    hostname: api2

  api3:
    <<: *api
    hostname: api3

  nginx:
    image: nginx:1.27-alpine
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
      - api3
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "30MB"

networks:
  backend:
    driver: bridge
