services:
  api1: &api
    build: .
    hostname: api1
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "100MB"

  api2:
    <<: *api
    hostname: api2

  api3:
    <<: *api
    hostname: api3

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "30MB"
